version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    container_name: api_container
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/mydatabase?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo_data: